### PR TITLE
Add parse result link relations

### PR DESCRIPTION
**Pull request by smizell**
See
https://github.com/refractproject/rfcs/blob/master/text/0009-parse-result-link-relations.md

### CODE REVIEW

**Comment by pksunkara** [comment]
@smizell An example would be nice here. How do I use the `origin` and `inferred` link relations?

**Comment by smizell** [comment]
@pksunkara This uses the `meta.links` and the [Link Element](https://github.com/refractproject/refract-spec/blob/master/refract-spec.md#link-element-element). This is just defining specific link relations you can use in context of those.

I'll be cleaning up the base spec in the coming days/weeks, so it will have a better explanation for this area there.

**Comment by pksunkara** [comment]
@smizell I understood about the `meta.links`. But please give me a small example?

**Comment by smizell** [comment]
@pksunkara Here is a current real-world example:

https://github.com/apiaryio/fury-adapter-swagger/blob/master/test/fixtures/refract/param-no-response.json#L7

This says there was an annotation issue, and the `origin` link tells the user the origin or the annotation. The link itself identifies the type of origin, and following the link gives you additional information about the annotation.

**Pull request merged**
